[공통] security, jwt Common 모듈로 이전
Team-Koreano/Koreano pull request #207
Opened 2024-06-20 08:32 UTC by hjm12223

## 개요

isuue : #201 
## PR 유형
어떤 변경 사항이 있나요?

- [x] 코드 리팩토링
- [x] 주석 추가 및 수정
- [x] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [x] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [x] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.) 
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

> ### Description

- 시큐리티와 JWT 를 Common 모듈로 이전하였습니다.

> ### Core Code

```java
package org.ecommerce.userapi.external.service;

import java.util.Set;
import java.util.concurrent.TimeUnit;

import javax.crypto.SecretKey;

import org.ecommerce.common.provider.JwtProvider;
import org.ecommerce.userapi.provider.RedisProvider;
import org.springframework.stereotype.Service;

import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class SellerTokenService {
	private static final long ONE_HOUR = 3_600;
	private static final long TWO_WEEKS = ONE_HOUR * 24 * 14;

	private final SecretKey secretKey;

	private final RedisProvider redisProvider;

	private final JwtProvider jwtProvider;

	public String createSellerTokens(Integer sellerId, Set<String> authorization,
		HttpServletResponse response) {

		final String accessToken = jwtProvider.createToken(sellerId,
			ONE_HOUR, secretKey, authorization);
		final String refreshToken = jwtProvider.createToken(sellerId,
			TWO_WEEKS, secretKey, authorization);

		String accessTokenKey = jwtProvider.getAccessTokenKey(sellerId, jwtProvider.getRoll(accessToken));
		redisProvider.setData(accessTokenKey, accessToken, ONE_HOUR, TimeUnit.SECONDS);

		String refreshTokenKey = jwtProvider.getRefreshTokenKey(sellerId, jwtProvider.getRoll(refreshToken));
		redisProvider.setData(refreshTokenKey, refreshToken, TWO_WEEKS, TimeUnit.SECONDS);

		response.addCookie(jwtProvider.createCookie(refreshToken));

		return accessToken;
	}

	public void removeTokens(String accessTokenKey, String refreshTokenKey) {
		redisProvider.deleteData(accessTokenKey);
		redisProvider.deleteData(refreshTokenKey);
	}
}

```
jwtProvider 의 Create 와 Remove 로직을 Service 로 분리하였습니다

2024-06-23 11:04 UTC, dodari5882 requested changes

2024-06-23 11:04 UTC, dodari5882 commented on common/src/main/java/org/ecommerce/common/config/BeanConfiguration.java
> +	public ProviderManager providerManager(@Qualifier("customAuthProvider") CustomAuthProvider authProvider) {
Qualifier 필요 없을듯 한데요?

2024-06-26 10:38 UTC, no-oneho approved these changes

2024-06-27 05:00 UTC, zmfpdl64 approved these changes

2024-06-27 05:06 UTC, zmfpdl64 approved these changes
ControllerTest로 공통 필드들을 묶으셨군요!! Filter를 제외하는 설정도 잘봤습니다 수고하셨습니다 종민님 👍

2024-06-27 05:06 UTC, zmfpdl64 commented on payment-api/src/test/resources/junit-platform.properties
> -junit.jupiter.execution.parallel.mode.default=concurrent
이 부분은 테스트 병렬처리 설정인데 제거하신 이유가 궁금합니다

2024-06-27 06:30 UTC, hjm12223 commented on payment-api/src/test/resources/junit-platform.properties
> -junit.jupiter.execution.parallel.mode.default=concurrent
아 우진님 말씀주셔서 감사합니다 이부분은 제가 실수로 삭제해버린거 같습니다 ㅠㅠ 바로 수정하도록 하겠습니다.

2024-06-27 09:56 UTC, Joowon-Seo approved these changes

2024-06-27 10:17 UTC, merged